# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request_review:
    types: [submitted]
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Push to Deployed Repo
        run: |
          cd $GITHUB_WORKSPACE
          git config user.name "runner"
          git config user.email "runner@runner"
          git checkout cleared
          git config --unset-all http.https://github.com/.extraheader
          git remote add deployed https://$GITHUB_TOKEN:$GITHUB_TOKEN@github.com/lesthaeghet/testrepo
          git push deployed master
