name: CI
on:
  pull_request_review:
    types: submitted
    branches: 'cleared'
  workflow_dispatch:
jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ref: 'cleared'
      - name: Pushes to public repo
        id: push_directory
        uses: lesthaeghet/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: $GITHUB_WORKSPACE
          destination-github-username: 'lesthaeghet'
          destination-repository-name: 'testrepo'
          user-email: noreply@noreply
          target-branch: main
